### ISSUE TITLE
Fieldplots

### ISSUE THREAD

**Issue by martejulie** [ngltr/sinaps#4]
I’m running the plotting notebook from the documentation and have a couple of questions/issues regarding the field plots. 

1. How are the positions on the y-axis mapped to the neuronal structure/sections? I think it would be of great value to clarify this in the documentation as well as in Figure 1 of the paper. 

2. The field plots are missing color bars.

**Comment by ngltr** [comment]
The field plot is modified to show also the neuron structure and a colormap represents the mapping between the y-axis and the neuronal structure
![image](https://user-images.githubusercontent.com/49352943/147866855-7f24ecf4-1b55-44c1-bafe-1d1559c74b0b.png)

**Comment by martejulie** [comment]
Please update Figure 1 in the paper accordingly. 

I would also like to encourage you to add units to the colorbars.

**Comment by cgurrr** [comment]
We have now added the units in the colorbar, and changed the figure in the paper.
